Spielzeugverleih/Spielzeugverleih/Controllers/ToyPicturesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Spielzeugverleih.Models;
using System.Drawing;
using System.IO;

namespace Spielzeugverleih.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ToyPicturesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ToyPictures
        public ActionResult Index()
        {
            return View(db.ToyPics.ToList());
        }

        // GET: ToyPictures/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToyPic toyPicture = db.ToyPics.Find(id);
            if (toyPicture == null)
            {
                return HttpNotFound();
            }
            return View(toyPicture);
        }

        // GET: ToyPictures/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ToyPictures/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ToyPictureId,Picture,ImagePath")] ToyPic toyPicture, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file.ContentLength > 0)
                {
                    MemoryStream target = new MemoryStream();
                    file.InputStream.CopyTo(target);
                    toyPicture.Picture = target.ToArray();

                    db.ToyPics.Add(toyPicture);
                    db.SaveChanges();
                    ViewBag.UploadSuccess = true;
                    return RedirectToAction("Index");
                }

            }

            return View(toyPicture);
        }

        // GET: ToyPictures/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToyPic toyPicture = db.ToyPics.Find(id);
            if (toyPicture == null)
            {
                return HttpNotFound();
            }
            return View(toyPicture);
        }

        // POST: ToyPictures/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ToyPictureId,Picture,ImagePath")] ToyPic toyPicture)
        {
            if (ModelState.IsValid)
            {
                db.Entry(toyPicture).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(toyPicture);
        }

        // GET: ToyPictures/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToyPic toyPicture = db.ToyPics.Find(id);
            if (toyPicture == null)
            {
                return HttpNotFound();
            }
            return View(toyPicture);
        }

        // POST: ToyPictures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ToyPic toyPicture = db.ToyPics.Find(id);
            db.ToyPics.Remove(toyPicture);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Spielzeugverleih/Spielzeugverleih/Views/ToyPictures/Create.cshtml
@model Spielzeugverleih.Models.ToyPic

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "ToyPictures", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Image</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="file" name="file" value="Browse" class="btn btn-default" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Spielzeugverleih/Spielzeugverleih/Views/ToyPictures/Delete.cshtml
@model Spielzeugverleih.Models.ToyPicture

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ToyPicture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Spielzeugverleih/Spielzeugverleih/Views/ToyPictures/Details.cshtml
@model Spielzeugverleih.Models.ToyPic

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ToyPicture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd>
            <img height="100" width="100" src="data:image;base64,@Convert.ToBase64String(Model.Picture)" />
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ToyPicId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Spielzeugverleih/Spielzeugverleih/Views/ToyPictures/Edit.cshtml
@model Spielzeugverleih.Models.ToyPicture

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ToyPicture</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ToyPictureId)

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Spielzeugverleih/Spielzeugverleih/Views/ToyPictures/Index.cshtml
@model IEnumerable<Spielzeugverleih.Models.ToyPic>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Picture)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <img height="100" width="100" src="data:image;base64,@Convert.ToBase64String(item.Picture)" />
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ToyPicId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ToyPicId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ToyPicId })
        </td>
    </tr>
}

</table>